name: Chat App Pipeline

on:
 push:
   branches: [main]
 pull_request:
   branches: [main]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout_code
       uses: actions/checkout@v4
     
     - name: setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '18'

     - name: Test client
       run: |
         cd client
         npm install
         npm audit --audit-level=high || true
         npm test -- --watchAll=false --passWithNoTests

     - name: Test server
       run: |
         cd server
         npm install
         npm audit --audit-level=high || true
         node -c index.js

     - name: Set up Docker
       uses: docker/setup-buildx-action@v3

     - name: build and deploy
       run: |
         docker compose up --build -d

     - name: Debug-check containers
       run: |
         docker compose ps
         docker compose logs

     - name: Test deployed App
       run: |
         sleep 30
         curl http://localhost:3000
         curl http://localhost:3001 || echo "Server connection failed"